[package]
name = "media_player"
version = "1.0.0"
edition = "2024"

[dependencies]
eframe = "0.35.0"
keepawake = "0.6.0"
rfd = "0.17.2"
rodio = "0.22.2"

[dependencies.ffmpeg-next]
version = "8.1.0"
features = [
    "build",   # Автоматично завантажує та компілює вихідний код FFmpeg під час cargo build
    "static",  # Лінкує отримані бібліотеки статично у твій бінарник
]
